### ISSUE TITLE
ModuleNotFoundError: No module named 'video_reading_benchmarks.camgear'

### ISSUE THREAD

**Issue by flying-monk** [bml1g12/benchmarking_video_reading_python#3]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from video_reading_benchmarks.benchmarks import baseline_benchmark, imutils_benchmark, \
  File "/usr/local/lib/python3.8/dist-packages/video_reading_benchmarks-X-py3.8.egg/video_reading_benchmarks/benchmarks.py", line 16, in <module>
    from video_reading_benchmarks.camgear.camgear import CamGear
ModuleNotFoundError: No module named 'video_reading_benchmarks.camgear'

**Comment by bml1g12** [comment]
From the root of the repo, you need to run `pip install -e .`  (or `pip install .`) to install this library. I've fixed a typo in the install instructions https://github.com/bml1g12/benchmarking_video_reading_python/blob/main/README.md#how-to-run

Keep me posted if you have any issues but I'll close for now as I think that should resolve your issue

```
 ─╮
╰─❯ pip install -e .                                                                                                                                                                                                 ─╯

╰─❯ python                                                                                                                                                                                                           ─╯
Python 3.7.15 (default, Nov  7 2022, 22:00:21) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from video_reading_benchmarks.camgear.camgear import CamGear
>>>
```
